name: Build Binary Executable

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - run: arm-none-eabi-gcc --version
      - name: Run make
        run: |
          make
          make can_build
          cd openblt_f446re
          make

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/*.bin
            build/*.elf
            build/*.hex
            openblt_f446re/build/*.bin
            openblt_f446re/build/*.elf
            openblt_f446re/build/*.hex

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            build/*.bin
            build/*.elf
            build/*.hex
            openblt_f446re/build/*.bin
            openblt_f446re/build/*.elf
            openblt_f446re/build/*.hex
          asset_name: |
            sensorboard.bin
            sensorboard.elf
            sensorboard.hex
          asset_content_type: application/octet-stream
            
